lib: [
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/Events.re"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/META"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/Util.re"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/dune-package"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.a"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cma"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cmi"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cmt"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cmx"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cmxa"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.cmxs"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib.ml"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Events.cmi"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Events.cmt"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Events.cmx"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Util.cmi"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Util.cmt"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/lib__Util.cmx"
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/lib/quizzy-stream/opam"
]
bin: [
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/bin/Hello"
]
doc: [
  "/home/thomas/Workspace/playing_with_projections_group/stream/_esy/default/store/b/quizzy_stream-873c9482/install/default/doc/quizzy-stream/README.md"
]
